server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      persistent: true
    context-path: '/api/v1'
#      timeout: 12h

spring:
  datasource:
    username: root
    password: "packy_mysql"
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/packy?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&serverTimezone=GMT"
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 10TB
      max-file-size: 1TB
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: debug
