
logging:
  level:
    root: info

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    password: "packy_mysql"
    url: "jdbc:mysql://localhost:3306/packy?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&serverTimezone=GMT"
